/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import javax.swing.JLabel;
import javax.swing.JTextField;
import operativosjimenezmarcano2.Main;

/**
 *
 * @author Miguel
 */
public class BattleInterface extends javax.swing.JFrame {

    /**
     * Creates new form BattleInterface
     */
    public BattleInterface() {
        initComponents();
        this.setVisible(true);
        aiTimer.setText(String.valueOf(Main.simulation.getBattleDuration()/1000));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        victoriesLabel = new javax.swing.JLabel();
        vsLabel = new javax.swing.JLabel();
        result = new javax.swing.JLabel();
        avatarPanel = new javax.swing.JPanel();
        avatarLogo = new javax.swing.JLabel();
        avatarVictories = new javax.swing.JLabel();
        aiStatusLabel = new javax.swing.JLabel();
        aiStatus = new javax.swing.JLabel();
        level1Label = new javax.swing.JLabel();
        level1Avatar = new javax.swing.JLabel();
        level2Label = new javax.swing.JLabel();
        level2Avatar = new javax.swing.JLabel();
        level3Label = new javax.swing.JLabel();
        level3Avatar = new javax.swing.JLabel();
        reinforceLabel = new javax.swing.JLabel();
        reinforceAvatar = new javax.swing.JLabel();
        avatarFighter = new javax.swing.JLabel();
        skillIcon = new javax.swing.JLabel();
        skillValueAvatar = new javax.swing.JLabel();
        heartIcon = new javax.swing.JLabel();
        healthValueAvatar = new javax.swing.JLabel();
        strengthIcon = new javax.swing.JLabel();
        strengthValueAvatar = new javax.swing.JLabel();
        agilityIcon = new javax.swing.JLabel();
        agilityValueAvatar = new javax.swing.JLabel();
        characterNameAvatar = new javax.swing.JLabel();
        regularShowPanel = new javax.swing.JPanel();
        regularShowLogo = new javax.swing.JLabel();
        regularShowVictories = new javax.swing.JLabel();
        level1Label1 = new javax.swing.JLabel();
        level1RegularShow = new javax.swing.JLabel();
        level2Label1 = new javax.swing.JLabel();
        level2RegularShow = new javax.swing.JLabel();
        level3Label1 = new javax.swing.JLabel();
        level3RegularShow = new javax.swing.JLabel();
        reinforceLabel1 = new javax.swing.JLabel();
        reinforceRegularShow = new javax.swing.JLabel();
        aiTimerLabel = new javax.swing.JLabel();
        aiTimer = new javax.swing.JTextField();
        changeTimeButton = new javax.swing.JButton();
        regularShowFighter = new javax.swing.JLabel();
        heartIcon1 = new javax.swing.JLabel();
        agilityValueRegularShow = new javax.swing.JLabel();
        agilityIcon1 = new javax.swing.JLabel();
        healthValueRegularShow = new javax.swing.JLabel();
        strengthIcon1 = new javax.swing.JLabel();
        strengthValueRegularShow = new javax.swing.JLabel();
        skillIcon1 = new javax.swing.JLabel();
        skillValueRegularShow = new javax.swing.JLabel();
        characterNameRegularShow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        victoriesLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        victoriesLabel.setText("VICTORIAS");
        getContentPane().add(victoriesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        vsLabel.setFont(new java.awt.Font("Segoe UI", 3, 90)); // NOI18N
        vsLabel.setText("VS");
        getContentPane().add(vsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, -1));

        result.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        result.setText("Aang le metió el palo a Mordecai");
        getContentPane().add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 660, 1010, -1));

        avatarPanel.setBackground(new java.awt.Color(255, 243, 207));
        avatarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        avatarLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/Logo_de_Avatar_la_leyenda_de_Aang-420.png"))); // NOI18N
        avatarPanel.add(avatarLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        avatarVictories.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        avatarVictories.setText("0");
        avatarPanel.add(avatarVictories, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 130, -1));

        aiStatusLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aiStatusLabel.setText("Estatus de la IA:");
        avatarPanel.add(aiStatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        aiStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        aiStatus.setText("Anunciando resultado");
        avatarPanel.add(aiStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 320, -1));

        level1Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        level1Label.setText("Nivel 1");
        avatarPanel.add(level1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        level1Avatar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        level1Avatar.setText("| id1 | id2 |");
        avatarPanel.add(level1Avatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 290, -1));

        level2Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        level2Label.setText("Nivel 2");
        avatarPanel.add(level2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        level2Avatar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        level2Avatar.setText("| id1 | id2 |");
        avatarPanel.add(level2Avatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 290, -1));

        level3Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        level3Label.setText("Nivel 3");
        avatarPanel.add(level3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        level3Avatar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        level3Avatar.setText("| id1 | id2 |");
        avatarPanel.add(level3Avatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 290, -1));

        reinforceLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reinforceLabel.setText("Refuerzo");
        avatarPanel.add(reinforceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        reinforceAvatar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        reinforceAvatar.setText("| id1 | id2 |");
        avatarPanel.add(reinforceAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 300, -1));

        avatarFighter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/Avatar/Avatar_Aang1.png"))); // NOI18N
        avatarFighter.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        avatarPanel.add(avatarFighter, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, 280));

        skillIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/skill1.png"))); // NOI18N
        avatarPanel.add(skillIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 580, -1, -1));

        skillValueAvatar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        skillValueAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        skillValueAvatar.setText("0");
        avatarPanel.add(skillValueAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 620, 50, -1));

        heartIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/heartIcon1.png"))); // NOI18N
        avatarPanel.add(heartIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, -1, -1));

        healthValueAvatar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        healthValueAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        healthValueAvatar.setText("0");
        avatarPanel.add(healthValueAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, 50, -1));

        strengthIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/weight1.png"))); // NOI18N
        avatarPanel.add(strengthIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 580, -1, -1));

        strengthValueAvatar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        strengthValueAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        strengthValueAvatar.setText("0");
        avatarPanel.add(strengthValueAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 620, 50, -1));

        agilityIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/agility1.png"))); // NOI18N
        avatarPanel.add(agilityIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 580, -1, -1));

        agilityValueAvatar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        agilityValueAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agilityValueAvatar.setText("0");
        avatarPanel.add(agilityValueAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 620, 50, -1));

        characterNameAvatar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        characterNameAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        characterNameAvatar.setText("Aang");
        avatarPanel.add(characterNameAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 260, 30));

        getContentPane().add(avatarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 740));

        regularShowPanel.setBackground(new java.awt.Color(83, 92, 145));
        regularShowPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regularShowLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/Regular_Show_Logo-450.png"))); // NOI18N
        regularShowPanel.add(regularShowLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        regularShowVictories.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        regularShowVictories.setForeground(new java.awt.Color(255, 255, 255));
        regularShowVictories.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        regularShowVictories.setText("0");
        regularShowPanel.add(regularShowVictories, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 130, -1));

        level1Label1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        level1Label1.setForeground(new java.awt.Color(255, 255, 255));
        level1Label1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        level1Label1.setText("Nivel 1");
        regularShowPanel.add(level1Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, -1));

        level1RegularShow.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        level1RegularShow.setForeground(new java.awt.Color(255, 255, 255));
        level1RegularShow.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        level1RegularShow.setText("| id2 | id1 |");
        regularShowPanel.add(level1RegularShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 220, 330, -1));

        level2Label1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        level2Label1.setForeground(new java.awt.Color(255, 255, 255));
        level2Label1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        level2Label1.setText("Nivel 2");
        regularShowPanel.add(level2Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, -1, -1));

        level2RegularShow.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        level2RegularShow.setForeground(new java.awt.Color(255, 255, 255));
        level2RegularShow.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        level2RegularShow.setText("| id2 | id1 |");
        regularShowPanel.add(level2RegularShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 280, 330, -1));

        level3Label1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        level3Label1.setForeground(new java.awt.Color(255, 255, 255));
        level3Label1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        level3Label1.setText("Nivel 3");
        regularShowPanel.add(level3Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, -1, -1));

        level3RegularShow.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        level3RegularShow.setForeground(new java.awt.Color(255, 255, 255));
        level3RegularShow.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        level3RegularShow.setText("| id2 | id1 |");
        regularShowPanel.add(level3RegularShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 340, 330, -1));

        reinforceLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reinforceLabel1.setForeground(new java.awt.Color(255, 255, 255));
        reinforceLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        reinforceLabel1.setText("Refuerzo");
        regularShowPanel.add(reinforceLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, -1, -1));

        reinforceRegularShow.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        reinforceRegularShow.setForeground(new java.awt.Color(255, 255, 255));
        reinforceRegularShow.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        reinforceRegularShow.setText("| id2 | id1 |");
        regularShowPanel.add(reinforceRegularShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 400, 330, -1));

        aiTimerLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aiTimerLabel.setForeground(new java.awt.Color(255, 255, 255));
        aiTimerLabel.setText("Control de tiempo de trabajo de la IA:");
        regularShowPanel.add(aiTimerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        aiTimer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        regularShowPanel.add(aiTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 120, -1));

        changeTimeButton.setText("Cambiar");
        changeTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeTimeButtonActionPerformed(evt);
            }
        });
        regularShowPanel.add(changeTimeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        regularShowFighter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/RegularShow/Mordecai.png"))); // NOI18N
        regularShowFighter.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        regularShowPanel.add(regularShowFighter, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, 280));

        heartIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/heartIcon1.png"))); // NOI18N
        regularShowPanel.add(heartIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, -1, -1));

        agilityValueRegularShow.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        agilityValueRegularShow.setForeground(new java.awt.Color(255, 255, 255));
        agilityValueRegularShow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agilityValueRegularShow.setText("0");
        regularShowPanel.add(agilityValueRegularShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 620, 50, -1));

        agilityIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/agility1.png"))); // NOI18N
        regularShowPanel.add(agilityIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 580, -1, -1));

        healthValueRegularShow.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        healthValueRegularShow.setForeground(new java.awt.Color(255, 255, 255));
        healthValueRegularShow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        healthValueRegularShow.setText("0");
        regularShowPanel.add(healthValueRegularShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 620, 50, -1));

        strengthIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/weight1.png"))); // NOI18N
        regularShowPanel.add(strengthIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 580, -1, -1));

        strengthValueRegularShow.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        strengthValueRegularShow.setForeground(new java.awt.Color(255, 255, 255));
        strengthValueRegularShow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        strengthValueRegularShow.setText("0");
        regularShowPanel.add(strengthValueRegularShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, 50, -1));

        skillIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/skill1.png"))); // NOI18N
        regularShowPanel.add(skillIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, -1, -1));

        skillValueRegularShow.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        skillValueRegularShow.setForeground(new java.awt.Color(255, 255, 255));
        skillValueRegularShow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        skillValueRegularShow.setText("0");
        regularShowPanel.add(skillValueRegularShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 50, -1));

        characterNameRegularShow.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        characterNameRegularShow.setForeground(new java.awt.Color(255, 255, 255));
        characterNameRegularShow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        characterNameRegularShow.setText("Mordecai");
        regularShowPanel.add(characterNameRegularShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 280, 30));

        getContentPane().add(regularShowPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 620, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_changeTimeButtonActionPerformed
        Main.simulation.setBattleDuration((int) (Float.parseFloat(aiTimer.getText())*1000));
    }// GEN-LAST:event_changeTimeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BattleInterface.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BattleInterface.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BattleInterface.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BattleInterface.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BattleInterface().setVisible(true);
            }
        });
    }

    public JLabel getAgilityValueAvatar() {
        return agilityValueAvatar;
    }

    public void setAgilityValueAvatar(JLabel agilityValueAvatar) {
        this.agilityValueAvatar = agilityValueAvatar;
    }

    public JLabel getAgilityValueRegularShow() {
        return agilityValueRegularShow;
    }

    public void setAgilityValueRegularShow(JLabel agilityValueRegularShow) {
        this.agilityValueRegularShow = agilityValueRegularShow;
    }

    public JLabel getHealthValueAvatar() {
        return healthValueAvatar;
    }

    public void setHealthValueAvatar(JLabel healthValueAvatar) {
        this.healthValueAvatar = healthValueAvatar;
    }

    public JLabel getHealthValueRegularShow() {
        return healthValueRegularShow;
    }

    public void setHealthValueRegularShow(JLabel healthValueRegularShow) {
        this.healthValueRegularShow = healthValueRegularShow;
    }

    public JLabel getResult() {
        return result;
    }

    public void setResult(JLabel result) {
        this.result = result;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agilityIcon;
    private javax.swing.JLabel agilityIcon1;
    private javax.swing.JLabel agilityValueAvatar;
    private javax.swing.JLabel agilityValueRegularShow;
    private javax.swing.JLabel aiStatus;
    private javax.swing.JLabel aiStatusLabel;
    private javax.swing.JTextField aiTimer;
    private javax.swing.JLabel aiTimerLabel;
    private javax.swing.JLabel avatarFighter;
    private javax.swing.JLabel avatarLogo;
    private javax.swing.JPanel avatarPanel;
    private javax.swing.JLabel avatarVictories;
    private javax.swing.JButton changeTimeButton;
    private javax.swing.JLabel characterNameAvatar;
    private javax.swing.JLabel characterNameRegularShow;
    private javax.swing.JLabel healthValueAvatar;
    private javax.swing.JLabel healthValueRegularShow;
    private javax.swing.JLabel heartIcon;
    private javax.swing.JLabel heartIcon1;
    private javax.swing.JLabel level1Avatar;
    private javax.swing.JLabel level1Label;
    private javax.swing.JLabel level1Label1;
    private javax.swing.JLabel level1RegularShow;
    private javax.swing.JLabel level2Avatar;
    private javax.swing.JLabel level2Label;
    private javax.swing.JLabel level2Label1;
    private javax.swing.JLabel level2RegularShow;
    private javax.swing.JLabel level3Avatar;
    private javax.swing.JLabel level3Label;
    private javax.swing.JLabel level3Label1;
    private javax.swing.JLabel level3RegularShow;
    private javax.swing.JLabel regularShowFighter;
    private javax.swing.JLabel regularShowLogo;
    private javax.swing.JPanel regularShowPanel;
    private javax.swing.JLabel regularShowVictories;
    private javax.swing.JLabel reinforceAvatar;
    private javax.swing.JLabel reinforceLabel;
    private javax.swing.JLabel reinforceLabel1;
    private javax.swing.JLabel reinforceRegularShow;
    private javax.swing.JLabel result;
    private javax.swing.JLabel skillIcon;
    private javax.swing.JLabel skillIcon1;
    private javax.swing.JLabel skillValueAvatar;
    private javax.swing.JLabel skillValueRegularShow;
    private javax.swing.JLabel strengthIcon;
    private javax.swing.JLabel strengthIcon1;
    private javax.swing.JLabel strengthValueAvatar;
    private javax.swing.JLabel strengthValueRegularShow;
    private javax.swing.JLabel victoriesLabel;
    private javax.swing.JLabel vsLabel;
    // End of variables declaration//GEN-END:variables

    public JLabel getSkillValueAvatar() {
        return skillValueAvatar;
    }

    public void setSkillValueAvatar(JLabel skillValueAvatar) {
        this.skillValueAvatar = skillValueAvatar;
    }

    public JLabel getSkillValueRegularShow() {
        return skillValueRegularShow;
    }

    public void setSkillValueRegularShow(JLabel skillValueRegularShow) {
        this.skillValueRegularShow = skillValueRegularShow;
    }

    public JLabel getStrengthValueAvatar() {
        return strengthValueAvatar;
    }

    public void setStrengthValueAvatar(JLabel strengthValueAvatar) {
        this.strengthValueAvatar = strengthValueAvatar;
    }

    public JLabel getStrengthValueRegularShow() {
        return strengthValueRegularShow;
    }

    public void setStrengthValueRegularShow(JLabel strengthValueRegularShow) {
        this.strengthValueRegularShow = strengthValueRegularShow;
    }

    public JLabel getAiStatus() {
        return aiStatus;
    }

    public void setAiStatus(JLabel aiStatus) {
        this.aiStatus = aiStatus;
    }

    public JTextField getAiTimer() {
        return aiTimer;
    }

    public void setAiTimer(JTextField aiTimer) {
        this.aiTimer = aiTimer;
    }

    public JLabel getAvatarFighter() {
        return avatarFighter;
    }

    public void setAvatarFighter(JLabel avatarFighter) {
        this.avatarFighter = avatarFighter;
    }

    public JLabel getAvatarVictories() {
        return avatarVictories;
    }

    public void setAvatarVictories(JLabel avatarVictories) {
        this.avatarVictories = avatarVictories;
    }

    public JLabel getLevel1Avatar() {
        return level1Avatar;
    }

    public void setLevel1Avatar(JLabel level1Avatar) {
        this.level1Avatar = level1Avatar;
    }

    public JLabel getLevel1RegularShow() {
        return level1RegularShow;
    }

    public void setLevel1RegularShow(JLabel level1RegularShow) {
        this.level1RegularShow = level1RegularShow;
    }

    public JLabel getLevel2Avatar() {
        return level2Avatar;
    }

    public void setLevel2Avatar(JLabel level2Avatar) {
        this.level2Avatar = level2Avatar;
    }

    public JLabel getLevel2RegularShow() {
        return level2RegularShow;
    }

    public void setLevel2RegularShow(JLabel level2RegularShow) {
        this.level2RegularShow = level2RegularShow;
    }

    public JLabel getLevel3Avatar() {
        return level3Avatar;
    }

    public void setLevel3Avatar(JLabel level3Avatar) {
        this.level3Avatar = level3Avatar;
    }

    public JLabel getLevel3RegularShow() {
        return level3RegularShow;
    }

    public void setLevel3RegularShow(JLabel level3RegularShow) {
        this.level3RegularShow = level3RegularShow;
    }

    public JLabel getRegularShowFighter() {
        return regularShowFighter;
    }

    public void setRegularShowFighter(JLabel regularShowFighter) {
        this.regularShowFighter = regularShowFighter;
    }

    public JLabel getRegularShowVictories() {
        return regularShowVictories;
    }

    public void setRegularShowVictories(JLabel regularShowVictories) {
        this.regularShowVictories = regularShowVictories;
    }

    public JLabel getReinforceAvatar() {
        return reinforceAvatar;
    }

    public void setReinforceAvatar(JLabel reinforceAvatar) {
        this.reinforceAvatar = reinforceAvatar;
    }

    public JLabel getReinforceRegularShow() {
        return reinforceRegularShow;
    }

    public void setReinforceRegularShow(JLabel reinforceRegularShow) {
        this.reinforceRegularShow = reinforceRegularShow;
    }

    public JLabel getCharacterNameAvatar() {
        return characterNameAvatar;
    }

    public void setCharacterNameAvatar(JLabel characterNameAvatar) {
        this.characterNameAvatar = characterNameAvatar;
    }

    public JLabel getCharacterNameRegularShow() {
        return characterNameRegularShow;
    }

    public void setCharacterNameRegularShow(JLabel characterNameRegularShow) {
        this.characterNameRegularShow = characterNameRegularShow;
    }

}
